### ISSUE TITLE
Не прикрепляется файл при включенном плагине

### ISSUE THREAD

**Issue by IlyaRu94** [yesworld/plugin-wp-optimize-image#10]
Плагин очень понравился, но есть у него достаточно обидный глюк. Сам плагин умеет работать только с изображениями. Если к форме нужно прикрепить .doc или .pdf - то про это можно забыть. Пробовал добавлять отдельное поле для прикрепления прочих файлов, но если в это поле добавить файл - он не будет прикреплён к письму. Видимо, плагин блокирует другие поля для прикрепления файлов. Прикрепление файлов к письму будет работать лишь в том случае, если полностью отключить данный плагин. Судя по вопросам на портале wordpress я не один сталкиваюсь с подобной проблемой. Что с этим делать? Было бы идеально, если бы плагин работал не только с изображениями, но и загружал (без всяких сжатий) другие файлы... Если это можно сделать лёгкой правкой кода - подскажите в каком месте изменить плагин, я поправлю сам. Просто возможность прикрепить к форме doc и pdf нам очень нужна.

**Comment by yesworld** [comment]
Привет. Спасибо за фидбек.. я честно делал этот плагин просто для одного клиента, по сути под его нужды. Можно в теории конечно и добавить такую возможность, что ты описал, но времени пока воооообще нет. %(

У тебя получается с какими плагинами косяк был?
Можешь еще другие альтернативные плагины глянуть на совместную работу? 
Еще желательно их версии написать, чтобы можно было повторить твою проблему.  

P.s. Если есть желание, можешь создать ПР, будет тебе большим плюсом в карму и в развитие проекта. 😀

**Comment by IlyaRu94** [comment]
Версия WP: 5.8.1, 
Версия Contact form 7: 5.5.2
Версия Images Optimize and Upload CF7: 2.1.2

Так же установлен плагин:
MultiLine files for Contact Form 7 Версия 2.0 (если Ваш плагин сможет подкреплять прочие файлы, по мимо картинок - я от данного плагина откажусь).

Проблема наблюдается даже если воспользоваться стандартной формой прикрепления файла Contact Form 7
Еще какой-то плагин пробовал для прикрепления файлов, уже не помню, да и не очень это важно, потому что Images Optimize and Upload CF7 его так же глушил...

Если более точнее и грубо описать проблему - файл не аттачится к письму. Прикрепляются только фото и только из Images Optimize and Upload CF7. Даже если из формы убрать шорткод этого плагина - не поможет... Только отключение плагина...

У меня есть сайт для тестов плагинов. Если нет времени разворачивать WP и устанавливать плагины - могу дать доступ к админке, публичке и ftp (скажи только куда прислать данные). Там уже проблема развернута, только заменить в контактной форме адрес электронной почты на свой))). Но, предупреждаю, не пугайся, там плагинов стоит дофига, я на этом сайте все тестирую, местами дорабатываю перед выкладкой на основной сайт (я поддерживаю платформу дистанционного обучения для студентов на основе WP).

Ps: сорри, с сокращениями и терминологией пока не дружу, редкий гость сообществ... ПР - это как расшифровывается?))))

**Comment by yesworld** [comment]
PR - Pull requests/Пулл реквест. 

Ладно, я вникну на неделе и постараюсь найти время для решения данной проблемы. 
Спасибо за инфу.

**Comment by IlyaRu94** [comment]
И Вам большое спасибо за работу! Буду рад протестировать отредактированный плагин первым.)))

**Comment by yesworld** [comment]
@IlyaRu94 Я залили исправление пока что на гит, чтобы совместно работали плагины. Если есть желание можешь попробовать проверить. :)

На счет переделки пока не уверен, для этого может потребоваться больше времени. Найди меня в телеграмме, спишемся, потестируем. 
https://t.me/ayesworld

**Comment by bruklig** [comment]
Привет, @IlyaRu94 !

Я посмотрел твой сайт, и там была небольшая ошибка в настройке шаблона отправляемых писем Contact Form 7. 

В поле "Прикреплённые файлы" были шорткоды сразу от трёх плагинов: 

1. нативный [file] от плагина Contact Form 7
2. шотркод от MultiLine files for Contact Form 7 (который не обязательно ставить)
3. шорткод от Images Optimize and Upload CF7 (который тоже не обязателен)

А нужно было указать только нативный шорткод [file] от плагина Contact Form 7.

![image](https://user-images.githubusercontent.com/9574574/142451840-c4db6374-e944-4ccb-9ad8-caa926c5c573.png)

В таком случае всё работает нормально.

Спасибо! 

Рустам.
