### ISSUE TITLE
Uploaded files cannot be attached to emails

### ISSUE THREAD

**Issue by nhamphap2002** [yesworld/plugin-wp-optimize-image#12]
Hi Damir A.
I used your plugin the file upload was successful. But I can't add them in email. Can you help me with this error?
Thank you

**Comment by bruklig** [comment]
Hello, @nhamphap2002 !

Maybe you have the same issue as #14 

Is your field marked as required? If yes, we are aware of this issue and adding a fix in the next release.

Thank you!
